version: '3.7'

services:
    coinbase-workers:
        container_name: "coinbase_worker"
        build:
            context: ./
            dockerfile: Coinbase.BackgroundWorker/Dockerfile
        image: "rhe89/hub-coinbase-worker"

    coinbase-api:
        container_name: "coinbase_api"
        build: 
            context: ./
            dockerfile: Coinbase.Web.Api/Dockerfile
        image: "rhe89/hub-coinbase-api"