version: '3.7'

networks:
    default: 
        external:
            name: hub-network
            name: hub-db-network

services:
    coinbase-workers:
        container_name: "coinbase_worker"
        build:
            context: ./src/Coinbase
            dockerfile: Coinbase.BackgroundWorker/Dockerfile
        image: "coinbase/worker"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - SQL_DB_COINBASE=${SQL_DB_COINBASE}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network

    coinbase-api:
        container_name: "coinbase_api"
        build: 
            context: ./src/Coinbase
            dockerfile: Coinbase.Web.Api/Dockerfile
        image: "coinbase/api"
        hostname: "coinbase-api"
        ports:
            - "${COINBASE_API_PORT}:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=;http://+
            - SQL_DB_COINBASE=${SQL_DB_COINBASE}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network