version: '3.7'

services:
    coinbase-service-bus-queue-host:
        container_name: "coinbase_service_bus_queue_host"
        build:
            context: ./
            dockerfile: Coinbase.HostedServices.ServiceBusQueueHost/Dockerfile
        image: "rhe89/hub-coinbase-service-bus-queue-host"

    coinbase-scheduled-host:
        container_name: "coinbase_scheduled_host"
        build:
            context: ./
            dockerfile: Coinbase.HostedServices.ScheduledHost/Dockerfile
        image: "rhe89/hub-coinbase-scheduled-host"

    coinbase-api:
        container_name: "coinbase_api"
        build: 
            context: ./
            dockerfile: Coinbase.Web.Api/Dockerfile
        image: "rhe89/hub-coinbase-api"